export const awsExports={
    "REGION": process.env.REACT_APP_USER_POOL_REGION,
    "USER_POOL_ID": process.env.REACT_APP_AMPLIFY_USER_POOL_ID,
    "USER_POOL_APP_CLIENT_ID": process.env.REACT_APP_AMPLIFY_USER_POOL_APP_CLIENT_ID
}